#!/bin/bash

quit(){
	kill %1 %2
	wait
	echo
	echo "Successfully exited makecents-test"
	echo
	exit 0
}

if ! -v rasa &> /dev/null; then
	printf "Command rasa not found, please ensure env is configured and run makecents-setup if necessary\n"
	exit 0
fi

rasa run actions &
rasa x &
trap quit INT
wait
